app: query-manager-serverless
service: query-manager-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  mainFunction:
    handler: src/mainFunction.handler
    events:
      - httpApi:
          path: /users
          method: get
  medicosAgendasList:
    handler: src/agenda/controller/medicosAgendasController.listMedicosAgendas
    events:
      - httpApi:
          path: /agendas
          method: get
  medicosAgendasDelete:
    handler: src/agenda/controller/medicosAgendasController.removeMedicoAgenda
    events:
      - httpApi:
          path: /agendas/{id}
          method: delete
  medicosAgendasUpdate:
    handler: src/agenda/controller/medicosAgendasController.updateMedicoAgenda
    events:
      - httpApi:
          path: /agendas
          method: put
  agendamentoCreate:
    handler: src/agendamento/controller/agendamentoController.setAgendamento
    events:
      - httpApi:
          path: /agendamento
          method: post
  agendamentoList:
    handler: src/agendamento/controller/agendamentoController.getAllAgendamentos
    events:
      - httpApi:
          path: /agendamento
          method: get


plugins:
  - serverless-offline
  - serverless-plugin-typescript
