app: query-manager-serverless
service: query-manager-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:

  mainFunction:
    handler: src/mainFunction.handler
    events:
      - httpApi:
          path: /hello
          method: get

  medicosAgendasList:
    handler: src/agenda/controller/medicosAgendasController.listMedicosAgendas
    events:
      - httpApi:
          path: /agendas
          method: get

  medicosAgendasDelete:
    handler: src/agenda/controller/medicosAgendasController.removeMedicoAgenda
    events:
      - httpApi:
          path: /agendas/{id}
          method: delete

  medicosAgendasUpdate:
    handler: src/agenda/controller/medicosAgendasController.updateMedicoAgenda
    events:
      - httpApi:
          path: /agendas
          method: put

  agendamentoCreate:
    handler: src/agendamento/controller/agendamentoController.setAgendamento
    events:
      - httpApi:
          path: /agendamentos
          method: post

  agendamentoList:
    handler: src/agendamento/controller/agendamentoController.listAgendamentos
    events:
      - httpApi:
          path: /agendamentos
          method: get


plugins:
  - serverless-offline
  - serverless-plugin-typescript
