app: query-manager-serverless
service: query-manager-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  mainFunction:
    handler: src/mainFunction.handler
    events:
      - httpApi:
          path: /users
          method: get
  medicosAgendasController:
    handler: src/agenda/controller/medicosAgendasController.listAgendas
    events:
      - httpApi:
          path: /agendas
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
